name: bob_mobile
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  url_launcher: ^5.2.7
  firebase_auth: ^0.15.0+1
  firebase_core: ^0.4.2+1
  google_sign_in: ^4.0.14
  flutter_svg: ^0.15.0
  cloud_firestore: ^0.12.11
  json_annotation: ^3.0.0
  random_color: ^1.0.3
  intl: ^0.16.0
  provider: ^3.2.0
  autocomplete_textfield: ^1.7.3
  json_serializable: ^3.2.3
  flare_flutter: ^1.7.3
  flare_dart: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/anim/

